### ISSUE TITLE
Update to Bootstrap 3.4.0

### ISSUE THREAD

**Issue by coliff** [Rundiz-WP/bootstrap-basic#24]
This fixes an XSS issue so would be good to update.

REF: https://blog.getbootstrap.com/2018/12/13/bootstrap-3-4-0/

**Comment by ve3** [comment]
https://themes.trac.wordpress.org/ticket/63362

https://github.com/Rundiz-WP/bootstrap-basic/releases/tag/v1.1.1

Thank you.
