### ISSUE TITLE
Display Excerpt code

### ISSUE THREAD

**Issue by Hammer1980** [Rundiz-WP/bootstrap-basic#25]
I am looking at the code in content.php I want the posts to appear as excerpts with a link. It does it with search but not otherwise.  

Please can you explain how to make this without having to search. I don't want to use the  read more tag in the editor (Shift+Alt+T).

Thank you.

**Comment by ve3** [comment]
In the content.php looking around `entry-summary`.

```php
	<?php if (is_search()) { // Only display Excerpts for Search ?> 
	<div class="entry-summary">
		<?php the_excerpt(); ?> 
		<div class="clearfix"></div>
	</div><!-- .entry-summary -->
	<?php } else { ?> 
	<div class="entry-content">
		<?php the_content(bootstrapBasicMoreLinkText()); ?> 
		<div class="clearfix"></div>
		<?php 
		/**
		 * This wp_link_pages option adapt to use bootstrap pagination style.
		 * The other part of this pager is in inc/template-tags.php function name bootstrapBasicLinkPagesLink() which is called by wp_link_pages_link filter.
		 */
		wp_link_pages(array(
			'before' => '<div class="page-links">' . __('Pages:', 'bootstrap-basic') . ' <ul class="pagination">',
			'after'  => '</ul></div>',
			'separator' => ''
		));
		?> 
	</div><!-- .entry-content -->
	<?php } //endif; ?> 
```

You will see that `is_search()` condition is wrap and the `the_excerpt()` function is inside. The `else` condition will show the full content.
You can copy only excerpt code inside the `is_search()` condition into new file such as **content-listing.php** and call to `get_template_part('content', 'listing');` instead of `get_template_part('content', get_post_format());` in **index.php**, **archive.php**

**Comment by Hammer1980** [comment]
Thanks. I follow the actual idea of what you are saying but I am not sure how to actually code that.

Would you be able to show me, that way I can 'reverse engineer' in my head to understand how to do it. It's the only way I have managed to learn things in the past.  I don't understand how to code a page to call get_template_part('content', 'listing');  I usually chnage the code of existing things by trial and error but I just cannot work it out.

**Comment by Hammer1980** [comment]
Thank you.

I tried replacing `is_search() ` with `is_singular() ` but that doesn't seem to work.

I follow the actual idea of what you are saying but I am not sure how to actually code that. 
Would you be able to show me, that way I can 'reverse engineer' in my head to understand how to do it. It's the only way I have managed to learn things in the past.  I don't understand how to code a page to call `get_template_part('content', 'listing');`

I usually figure things out by trial and error but I just can't do it with this one.

**Comment by Hammer1980** [comment]
Have sorted it.  I changed `is_search()` to `is_home()` and it worked. Haven now changed to `(is_search() || is_home())` and both work.

**Comment by ve3** [comment]
Learn more about theme development from these sources:

* https://codex.wordpress.org/Theme_Development
* https://developer.wordpress.org/reference/functions/get_template_part/
* https://developer.wordpress.org/themes/basics/template-hierarchy/

**Comment by Hammer1980** [comment]
Thank you :)
