### ISSUE TITLE
latest update causing js conflicts

### ISSUE THREAD

**Issue by SeanYeaney** [Rundiz-WP/bootstrap-basic#26]
after update the latest version causes some js to stop working. conflict issues.

**Comment by ve3** [comment]
Could you give me more detail please?

This site is using Bootstrap Basic v1.1.3 and WordPress 5.4.1 but have no problems.
Console log show no errors and everything seems to working fine.

What is the URL that have conflict issues? I can inspect more detail from that URL.

**Comment by SeanYeaney** [comment]
It seems like a query conflict. We custom scripts and such that were working prior to the latest version and then the stop working and say jquery.example is not a function. Restoring to previous version of theme resolves the issue.

**Comment by ve3** [comment]
This theme did nothing about jQuery except move them to the bottom in version 1.1.2 ( see commit https://github.com/Rundiz-WP/bootstrap-basic/commit/b6cf78b59ad2d56480b3b58266556d4c9d94ff41 )

When you enqueue your script make sure that you use correct function between `get_template_directory_uri()` or `get_stylesheet_uri()` depend on your usage. ( see this question https://stackoverflow.com/questions/31797203/whats-the-difference-between-get-stylesheet-directory-uri-and-get-template-di )
If you are using correct function but need your script to load after some script on this theme, set the priority argument to `11` or more (higher number is lower priority and load after). See document about this here ( https://developer.wordpress.org/reference/functions/add_action/ )

And when you enqueue your script, make sure that you added `jquery` in third argument. ( see document here https://developer.wordpress.org/reference/functions/wp_enqueue_script/ )

I hope that you can make it work with the latest version to use latest feature (and fix) from Bootstrap 3.

**Comment by SeanYeaney** [comment]
got it. that makes sense.

**Comment by ve3** [comment]
I will close this issue for now, if you still have problem with this please reply and I can re-open it again.
