### ISSUE TITLE
Remove Borders

### ISSUE THREAD

**Issue by jessicaboggia** [Rundiz-WP/bootstrap-basic#30]
There's a white border around my sidebar widgets, pages, and content that I need to get rid of. When customizing this theme, how do you remove or change the ugly white reference borders around these items?

I have tried looking up the classes and IDs used for the elements and setting them to border: 0px in the custom css field but it does not seem to work. I feel like I am missing something obvious. 

Thanks!

**Comment by ve3** [comment]
Please post the link so that I can inspect the problem when I'm available.

**Comment by jessicaboggia** [comment]
Hi,

Thank you for getting back to me so quickly!!

Here is the link: http://umn.godsibb.net/ 

Thanks again!

**Comment by ve3** [comment]
It's in assets/css/main.css. You have to override this selector in your child theme. `#sidebar-left .widget, #sidebar-right .widget`.

Learn more about how to use inspector in [Chrome](https://developer.chrome.com/docs/devtools/open/), [Firefox](https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/open_the_inspector/index.html).

Learn more about [CSS overriding](https://www.w3docs.com/snippets/css/how-to-override-css-styles.html).
